name: 'KCJISU Auto Get Traffic'

on:
  push:
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Get traffic'
      env:
        KCJISU_EMAIL: ${{ secrets.KCJISU_EMAIL }}
        KCJISU_PASSWORD: ${{ secrets.KCJISU_PASSWORD }}
        KCJISU_DOMAIN: 'kcssr.icu'
      run: python kcjisu_get_traffics.py
